# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2017-10-03 03:36
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('recipeapp', '0002_recipe_auther'),
    ]

    operations = [
        migrations.AlterField(
            model_name='recipe',
            name='auther',
            field=models.CharField(max_length=20, null=True),
        ),
    ]
